In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score, precision_score, recall_score
from sklearn.linear_model import LogisticRegression
import statsmodels.api as sm

In [2]:
df = pd.read_csv(r"C:\Users\DELL\diabetes.csv")

In [3]:
df["Outcome"].value_counts(normalize=True)

Outcome
0    0.651042
1    0.348958
Name: proportion, dtype: float64

In [4]:
k = 5

In [5]:
X = df.drop(columns=["Outcome"])

In [6]:
y = df["Outcome"]

In [7]:
folds = np.random.choice(k, size=df.shape[0], replace=True)

In [8]:
X_train = X[folds!=0]
X_test = X[folds==0]
y_train = y[folds!=0]
y_test = y[folds==0]

In [9]:
clf = LogisticRegression()

In [10]:
clf.fit(X_train, y_train)

C:\Users\DELL\AppData\Roaming\Python\Python310\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [11]:
y_pred = clf.predict(X_test)

In [12]:
print(y_pred)

[0 1 1 0 0 0 0 1 0 1 0 0 0 0 0 0 1 0 1 0 0 0 0 0 1 0 0 0 1 0 1 0 0 0 1 1 0
 1 0 0 0 1 0 1 0 0 1 1 0 0 1 1 0 1 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 0 0 0 0
 0 0 1 0 0 0 1 1 1 0 0 0 1 0 1 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 1 0 0 1 1 0 1
 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0
 0 1 0 0 0 1 0 0 0 0 0 0 1 0 0]

In [13]:
coeff = clf.coef_
coeff

array([[ 0.12232742,  0.03350742, -0.0122231 ,  0.00560695, -0.00206919,
         0.08459975,  0.79137121,  0.01231493]])

In [14]:
intercept = clf.intercept_
intercept

array([-7.9307741])

In [15]:
X.shape

(768, 8)

In [16]:
len(clf.coef_[0])

8

In [17]:
prob = clf.predict_proba(X_test)
prob

array([[0.56033212, 0.43966788],
       [0.27124646, 0.72875354],
       [0.45794061, 0.54205939],
       [0.71172631, 0.28827369],
       [0.94234206, 0.05765794],
       [0.84999871, 0.15000129],
       [0.86398529, 0.13601471],
       [0.0535736 , 0.9464264 ],
       [0.9534374 , 0.0465626 ],
       [0.20590341, 0.79409659],
       [0.60933773, 0.39066227],
       [0.98753522, 0.01246478],
       [0.97287439, 0.02712561],
       [0.85156205, 0.14843795],
       [0.99701654, 0.00298346],
       [0.91514464, 0.08485536],
       [0.34360589, 0.65639411],
       [0.87714035, 0.12285965],
       [0.32848475, 0.67151525],
       [0.79817842, 0.20182158],
       [0.90718713, 0.09281287],
       [0.97637361, 0.02362639],
       [0.84064166, 0.15935834],
       [0.77098149, 0.22901851],
       [0.38277521, 0.61722479],
       [0.64789679, 0.35210321],
       [0.74983845, 0.25016155],
       [0.98994433, 0.01005567],
       [0.38294826, 0.61705174],
       [0.54748344, 0.45251656],
       [0.04376678, 0.95623322],
       [0.68304529, 0.31695471],
       [0.83060067, 0.16939933],
       [0.77880117, 0.22119883],
       [0.2582329 , 0.7417671 ],
       [0.36480083, 0.63519917],
       [0.64583532, 0.35416468],
       [0.22597883, 0.77402117],
       [0.62419   , 0.37581   ],
       [0.81148803, 0.18851197],
       [0.84612733, 0.15387267],
       [0.11523869, 0.88476131],
       [0.93710139, 0.06289861],
       [0.38418548, 0.61581452],
       [0.67225293, 0.32774707],
       [0.65030524, 0.34969476],
       [0.38360023, 0.61639977],
       [0.34724632, 0.65275368],
       [0.9207371 , 0.0792629 ],
       [0.87850937, 0.12149063],
       [0.19773417, 0.80226583],
       [0.39638914, 0.60361086],
       [0.63524974, 0.36475026],
       [0.2577428 , 0.7422572 ],
       [0.85691362, 0.14308638],
       [0.67862403, 0.32137597],
       [0.51970003, 0.48029997],
       [0.62860233, 0.37139767],
       [0.87165046, 0.12834954],
       [0.69549056, 0.30450944],
       [0.93016295, 0.06983705],
       [0.87317395, 0.12682605],
       [0.67916891, 0.32083109],
       [0.68661274, 0.31338726],
       [0.44217431, 0.55782569],
       [0.7991979 , 0.2008021 ],
       [0.30142991, 0.69857009],
       [0.8259157 , 0.1740843 ],
       [0.23996679, 0.76003321],
       [0.75008636, 0.24991364],
       [0.75638586, 0.24361414],
       [0.79208813, 0.20791187],
       [0.52073945, 0.47926055],
       [0.90822462, 0.09177538],
       [0.77592546, 0.22407454],
       [0.9468034 , 0.0531966 ],
       [0.27689215, 0.72310785],
       [0.7194893 , 0.2805107 ],
       [0.67060366, 0.32939634],
       [0.66134695, 0.33865305],
       [0.26162833, 0.73837167],
       [0.07461795, 0.92538205],
       [0.1605493 , 0.8394507 ],
       [0.73807064, 0.26192936],
       [0.71882524, 0.28117476],
       [0.95722776, 0.04277224],
       [0.1436475 , 0.8563525 ],
       [0.53064317, 0.46935683],
       [0.28436523, 0.71563477],
       [0.6817981 , 0.3182019 ],
       [0.86212569, 0.13787431],
       [0.92565327, 0.07434673],
       [0.64991598, 0.35008402],
       [0.89302872, 0.10697128],
       [0.89682945, 0.10317055],
       [0.96817249, 0.03182751],
       [0.88019087, 0.11980913],
       [0.07349007, 0.92650993],
       [0.89283749, 0.10716251],
       [0.68871688, 0.31128312],
       [0.89511941, 0.10488059],
       [0.36406689, 0.63593311],
       [0.82518355, 0.17481645],
       [0.60339665, 0.39660335],
       [0.11510377, 0.88489623],
       [0.85476526, 0.14523474],
       [0.9167361 , 0.0832639 ],
       [0.46102469, 0.53897531],
       [0.34784035, 0.65215965],
       [0.75121615, 0.24878385],
       [0.34660914, 0.65339086],
       [0.8918128 , 0.1081872 ],
       [0.71092498, 0.28907502],
       [0.74884646, 0.25115354],
       [0.91889067, 0.08110933],
       [0.78493656, 0.21506344],
       [0.80601925, 0.19398075],
       [0.71942278, 0.28057722],
       [0.31331917, 0.68668083],
       [0.80638112, 0.19361888],
       [0.14861696, 0.85138304],
       [0.86981397, 0.13018603],
       [0.89985603, 0.10014397],
       [0.89291962, 0.10708038],
       [0.74021743, 0.25978257],
       [0.5401054 , 0.4598946 ],
       [0.81994572, 0.18005428],
       [0.51403301, 0.48596699],
       [0.64308297, 0.35691703],
       [0.58623941, 0.41376059],
       [0.89765748, 0.10234252],
       [0.25149432, 0.74850568],
       [0.15392596, 0.84607404],
       [0.6256127 , 0.3743873 ],
       [0.67587522, 0.32412478],
       [0.82173592, 0.17826408],
       [0.48218915, 0.51781085],
       [0.84348272, 0.15651728],
       [0.81905452, 0.18094548],
       [0.86532884, 0.13467116],
       [0.89251637, 0.10748363],
       [0.91091612, 0.08908388],
       [0.76718861, 0.23281139],
       [0.94713633, 0.05286367],
       [0.54852032, 0.45147968],
       [0.83316892, 0.16683108],
       [0.42232126, 0.57767874],
       [0.68172965, 0.31827035],
       [0.90892586, 0.09107414],
       [0.14969622, 0.85030378],
       [0.93384863, 0.06615137],
       [0.86214624, 0.13785376],
       [0.78095474, 0.21904526],
       [0.34718481, 0.65281519],
       [0.55286195, 0.44713805],
       [0.74506909, 0.25493091],
       [0.74078822, 0.25921178],
       [0.87554109, 0.12445891],
       [0.79090628, 0.20909372],
       [0.67007522, 0.32992478],
       [0.19755587, 0.80244413],
       [0.8127144 , 0.1872856 ],
       [0.90633636, 0.09366364]])

In [18]:
coef = pd.DataFrame({ "Features":X.columns, "Coefficient":coeff[0]})
coef

                   Features  Coefficient
0               Pregnancies     0.122327
1                   Glucose     0.033507
2             BloodPressure    -0.012223
3             SkinThickness     0.005607
4                   Insulin    -0.002069
5                       BMI     0.084600
6  DiabetesPedigreeFunction     0.791371
7                       Age     0.012315

In [19]:
cf = confusion_matrix(y_test, y_pred)
cf

array([[102,   8],
       [ 18,  35]], dtype=int64)

In [20]:
acc = accuracy_score(y_test, y_pred)
acc

0.8404907975460123

In [21]:
recall = recall_score(y_test, y_pred)
recall

0.660377358490566

In [22]:
prec = precision_score(y_test, y_pred)
prec

0.813953488372093

In [23]:
f1 = f1_score(y_test, y_pred)
f1

0.7291666666666666

In [24]:
x_train_sm = sm.add_constant(X_train)
x_train_sm

,const,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,1.0,6,148,72,35,0,33.6,0.627,50
1,1.0,1,85,66,29,0,26.6,0.351,31
2,1.0,8,183,64,0,0,23.3,0.672,32
3,1.0,1,89,66,23,94,28.1,0.167,21
4,1.0,0,137,40,35,168,43.1,2.288,33
...,...,...,...,...,...,...,...,...,...
761,1.0,9,170,74,31,0,44.0,0.403,43
762,1.0,9,89,62,0,0,22.5,0.142,33
763,1.0,10,101,76,48,180,32.9,0.171,63
764,1.0,2,122,70,27,0,36.8,0.340,27
766,1.0,1,126,60,0,0,30.1,0.349,47

In [25]:
logit_model = sm.Logit(y_train, x_train_sm)
logit_model

In [52]:
result = logit_model.fit()
result

Optimization terminated successfully.
         Current function value: 0.489057
         Iterations 6

In [54]:
print(result.summary2())

                             Results: Logit
=========================================================================
Model:                  Logit              Pseudo R-squared:   0.248
Dependent Variable:     Outcome            AIC:                609.7584
Date:                   2026-05-01 11:45   BIC:                649.4055
No. Observations:       605                Log-Likelihood:     -295.88
Df Model:               8                  LL-Null:            -393.68
Df Residuals:           596                LLR p-value:        5.4003e-38
Converged:              1.0000             Scale:              1.0000
No. Iterations:         6.0000
-------------------------------------------------------------------------
                          Coef.  Std.Err.    z     P>|z|   [0.025  0.975]
-------------------------------------------------------------------------
const                    -7.8661   0.7736 -10.1685 0.0000 -9.3823 -6.3499
Pregnancies               0.1221   0.0355   3.4439 0.0006  0.0526  0.1916
Glucose                   0.0331   0.0040   8.2661 0.0000  0.0252  0.0409
BloodPressure            -0.0123   0.0057  -2.1808 0.0292 -0.0234 -0.0012
SkinThickness             0.0048   0.0076   0.6255 0.5316 -0.0102  0.0198
Insulin                  -0.0020   0.0011  -1.9359 0.0529 -0.0041  0.0000
BMI                       0.0845   0.0165   5.1119 0.0000  0.0521  0.1169
DiabetesPedigreeFunction  0.8595   0.3396   2.5311 0.0114  0.1940  1.5251
Age                       0.0118   0.0104   1.1349 0.2564 -0.0086  0.0323
=========================================================================

C:\ProgramData\anaconda3\lib\site-packages\statsmodels\iolib\summary2.py:579: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  dat = dat.applymap(lambda x: _formatter(x, float_format))

In [56]:
#### EXAMS QUESTIONS

In [151]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.metrics import confusion_matrix, classification_report, precision_score, recall_score
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [153]:
df = sns.load_dataset('titanic').dropna()

In [155]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
871,1,1,female,47.0,1,1,52.5542,S,First,woman,False,D,Southampton,yes,False
872,0,1,male,33.0,0,0,5.0000,S,First,man,True,B,Southampton,no,True
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True

In [157]:
df = pd.get_dummies(df)

In [159]:
df

,survived,pclass,age,sibsp,parch,fare,adult_male,alone,sex_female,sex_male,...,deck_C,deck_D,deck_E,deck_F,deck_G,embark_town_Cherbourg,embark_town_Queenstown,embark_town_Southampton,alive_no,alive_yes
1,1,1,38.0,1,0,71.2833,False,False,True,False,...,True,False,False,False,False,True,False,False,False,True
3,1,1,35.0,1,0,53.1000,False,False,True,False,...,True,False,False,False,False,False,False,True,False,True
6,0,1,54.0,0,0,51.8625,True,True,False,True,...,False,False,True,False,False,False,False,True,True,False
10,1,3,4.0,1,1,16.7000,False,False,True,False,...,False,False,False,False,True,False,False,True,False,True
11,1,1,58.0,0,0,26.5500,False,True,True,False,...,True,False,False,False,False,False,False,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
871,1,1,47.0,1,1,52.5542,False,False,True,False,...,False,True,False,False,False,False,False,True,False,True
872,0,1,33.0,0,0,5.0000,True,True,False,True,...,False,False,False,False,False,False,False,True,True,False
879,1,1,56.0,0,1,83.1583,False,False,True,False,...,True,False,False,False,False,True,False,False,False,True
887,1,1,19.0,0,0,30.0000,False,True,True,False,...,False,False,False,False,False,False,False,True,False,True
889,1,1,26.0,0,0,30.0000,True,True,False,True,...,True,False,False,False,False,True,False,False,False,True

In [161]:
df["survived"].value_counts(normalize=True)

survived
1    0.675824
0    0.324176
Name: proportion, dtype: float64

In [163]:
X = df.drop(columns=["survived"])

In [165]:
y = df["survived"]

In [167]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

In [169]:
sc = StandardScaler()

In [171]:
X_train = sc.fit_transform(X_train)

In [173]:
X_test = sc.transform(X_test)

In [175]:
model = LogisticRegression()

In [177]:
model.fit(X_train, y_train)

LogisticRegression()

In [179]:
y_pred = model.predict(X_test)

In [183]:
print(confusion_matrix(y_test, y_pred))

[[13  0]
 [ 0 24]]

In [185]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      1.00      1.00        24

    accuracy                           1.00        37
   macro avg       1.00      1.00      1.00        37
weighted avg       1.00      1.00      1.00        37